name: weather_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  google_fonts: ^2.1.0
  geolocator: ^7.7.0
  provider: ^6.0.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  sliding_up_panel: ^2.0.0+1

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
